name: CI/CD pour app A

on: 
  push:
    branches: 
      - main

jobs:
  build_push_docker-hub:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: appA
            directory: ./
            image: hayataf/app-a


    steps:
      # Nous donne accès au code python de l'app
      - name: Get appA code
        uses: actions/checkout@v4
      # Nous permet d'obtenir les 7 premiers caractères du hash du dernier commit
      - name: Get the hash of the last commit for the tag of new images
        run: echo "VERSION=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
      # Nous permet de nous connecter à Docker Hub
      - name: Connect to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      # Nous permet de construire et pousser notre image dans le repertoire Docker Hub 
      - name: Build and push the image ${{ matrix.name }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.directory }}
          file: ${{ matrix.directory }}Dockerfile
          push: true
          tags: ${{ matrix.image }}:${{ env.VERSION }}
